---
- name : Ansible playbook to install a package 
  hosts: all 
  gather_facts: no
  tasks:
      # - package:
      #     name: httpd
      #     state: present
      - command : cat /tmp/Demo/Demo.txt
        register: output
      - debug:
          msg: '{{ output.stdout }}'

      


