#Checking for the VMware shell module 

---
- name: Playbook to run a shell command on vm ware guest os 
  hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
    - vars.yaml
  tasks:

    - vmware_vm_shell:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: no
        datacenter: "{{datacenter}}"
        vm_username: "{{ user }}"
        vm_password: "{{ pass }}"
        vm_id: "{{ vm_name }}"
        vm_shell: echo
        vm_shell_args: $USER
        wait_for_process: True
        timeout: 2000
      register: shell_command_with_wait_timeout
      
    - debug:
            msg : '{{ shell_command_with_wait_timeout}}'  
